### ISSUE TITLE
Consider storing the data as honeybee JSONs instead of openstudio standards gem JSONs

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-energy-standards#16]
I am realizing that some of our other plugins (like that for Rhino and Revit) will likely want to take advantage of the OpenStudio standards gem data directly rather than through a Python extension as they have to right now.

I know @mingbopeng wants to do this for the Rhino plugin and, to do this right now, he would have to write a whole set of extra classmethods to parse the OpenStudio standards gem JSONs to his C# objects.

In light of this, maybe I should just set up the utilities of this repo to translate the OpenStudio standards gem JSONs over to Honeybee JSONs before writing them to the files that get used in the extension process. This way, Mingbo and Konrad can use their C# bindings to parse this data from files. This will mean that we are getting one step further from the original google spreadsheet that this data comes from but we already do so much processing/cleaning of this data already that we might as well go this extra mile.

What do you think @mostaphaRoudsari  and @mingbopeng ?

**Comment by MingboPeng** [comment]
@chriswmackey  actually, I do prefer this standard library to be saved as our honeybee schema JSON format. Which would make our side so much easier to use these library.

**Comment by chriswmackey** [comment]
I have done the first part of addressing this issue in that there's now data stored in honeybee JSONs:
https://github.com/ladybug-tools/honeybee-energy-standards/tree/master/honeybee_energy_standards/data
Now, I just have to make sure that these JSONs are used by the extension and not the OpenStdudio standards JSONs (which should eventually be deleted from the package).

In the meantime, the location of the Honeybee JSONs in the package will not change and the plan is to install this whole package to the `[USER]/honeybee/` folder. So this should give you what you need for now @MingboPeng .

**Comment by chriswmackey** [comment]
This has been addressed via https://github.com/ladybug-tools/honeybee-energy-standards/pull/23
