### ISSUE TITLE
Set Up Environment Variables on Travis

### ISSUE THREAD

**Issue by chriswmackey** [ladybug-tools/honeybee-energy-standards#5]
@mostaphaRoudsari ,

I just need you to put in the GH_TOKEN and PYPI_PASSWORD here:
https://travis-ci.org/ladybug-tools/honeybee-energy-standards/settings

Then you can restart the deployment job here:
https://travis-ci.org/ladybug-tools/honeybee-energy-standards/jobs/602946227

**Comment by mostaphaRoudsari** [comment]
It should be all set.
